<a href="https://colab.research.google.com/github/kushagrabhadauria21/Random_Forest_Regressor/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**importing libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

##**importing dataset**

In [2]:
df=pd.read_csv("Social_Network_Ads.csv")
X=df.iloc[:, 0:2].values
y=df.iloc[:, 2].values
X


array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


##**Splitting the dataset**

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.25, random_state=0)
y_test


array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1])

##**feature scaling**

In [4]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
np.set_printoptions(suppress=True, precision=2)
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)
X_test


array([[-0.8 ,  0.5 ],
       [-0.01, -0.57],
       [-0.31,  0.16],
       [-0.8 ,  0.27],
       [-0.31, -0.57],
       [-1.1 , -1.44],
       [-0.71, -1.58],
       [-0.21,  2.16],
       [-1.99, -0.05],
       [ 0.88, -0.77],
       [-0.8 , -0.6 ],
       [-1.  , -0.42],
       [-0.11, -0.42],
       [ 0.09,  0.22],
       [-1.8 ,  0.48],
       [-0.61,  1.37],
       [-0.11,  0.22],
       [-1.89,  0.45],
       [ 1.67,  1.75],
       [-0.31, -1.38],
       [-0.31, -0.65],
       [ 0.88,  2.16],
       [ 0.28, -0.54],
       [ 0.88,  1.03],
       [-1.5 , -1.21],
       [ 1.08,  2.07],
       [-1.  ,  0.5 ],
       [-0.9 ,  0.3 ],
       [-0.11, -0.22],
       [-0.61,  0.48],
       [-1.7 ,  0.53],
       [-0.11,  0.27],
       [ 1.87, -0.28],
       [-0.11, -0.48],
       [-1.4 , -0.34],
       [-1.99, -0.51],
       [-1.6 ,  0.33],
       [-0.41, -0.77],
       [-0.71, -1.03],
       [ 1.08, -0.97],
       [-1.1 ,  0.53],
       [ 0.28, -0.51],
       [-1.1 ,  0.42],
       [-0.

##**implementing Random Forest Classification**

In [5]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

##**predicting a result with random entry**

In [6]:
classifier.predict(sc.transform([[35, 75000]]))

array([0])

##**predicting the test set results and comaring**

In [7]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


##**making the confusion matrix and accuracy score**

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_pred, y_test)

[[63  5]
 [ 4 28]]


0.91

##**Visualising the Training Set Result**

In [10]:
from matplotlib.colors import ListedColormap

# Assuming you have defined the classifier and X_train, y_train, and sc variables before this code snippet

X_set, y_set = sc.inverse_transform(X_train), y_train

X1, X2 = np.meshgrid(np.arange(start=X_set[:, 0].min()-10, stop=X_set[:, 0].max()+10, step=0.25),
                     np.arange(start=X_set[:, 1].min()-1000, stop=X_set[:, 1].max()+1000, step=0.25))

plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha=0.75, cmap=ListedColormap(('red', 'green')))

plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())

for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c=ListedColormap(('red', 'green'))(i), label=j)

plt.title('Decision Tree Classification (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

<ipython-input-10-311bda90a67c>:17: UserWarning: *c* argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with *x* & *y*.  Please use the *color* keyword-argument or provide a 2D array with a single row if you intend to specify the same RGB or RGBA value for all points.
  plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c=ListedColormap(('red', 'green'))(i), label=j)
